.. vi: syntax=rst

======================
Documentation with RST
======================

:Author: Roland Puntaier

.. toctree::
   readme.rest
   ra.rest
   sr.rest
   dd.rest
   tp.rest
   rstdoc.rest


