.. vi: syntax=rst

.. _`rr1`:

:rr1: 

======
rstdoc
======

Documentation with RST
======================

.. include:: ../readme.rst


.. include:: _dcx.rst

.. include:: _dcx_api.rst



.. include:: _fromdocx.rst

.. include:: _fromdocx_api.rst



.. include:: _listtable.rst

.. include:: _listtable_api.rst


.. include:: _untable.rst

.. include:: _untable_api.rst


.. include:: _reflow.rst

.. include:: _reflow_api.rst


.. include:: _reimg.rst

.. include:: _reimg_api.rst


.. include:: _retable.rst

.. include:: _retable_api.rst



.. .. .. alternatively one could make a rstdoc.rest.stpl with
.. .. %import sys
.. .. %sys.path.append('..')
.. .. %from setup.py import read
.. .. 
.. .. {{read('readme.rst')}}
.. .. 
.. .. {{read('rstdoc/dcx.py')}}
.. .. 
.. .. {{read('rstdoc/fromdocx.py')}}
.. .. 
.. .. {{read('rstdoc/listtable.py')}}
.. .. 
.. .. {{read('rstdoc/untable.py')}}
.. .. 
.. .. {{read('rstdoc/reflow.py')}}
.. .. 
.. .. {{read('rstdoc/reimg.py')}}
.. .. 
.. .. {{read('rstdoc/retable.py')}}


.. include:: _links_sphinx.rst
