.. vi: syntax=rst

.. _`tkf`:

=========
Test Plan
=========

Purpose
=======

The |son| are tested by

- the motivations in the |rwx|
- this whole documentation

The tests here concentrate on |or1|.

Test Driver
===========

There are only automatic tests.

`pytest`_ and `tox`_ are used to run the tests.

.. include:: ../tox.ini
    :literal:

To run `tox`_, in the root folder, enter::

    tox

To run `pytest`_, in the root folder, enter::

    py.test

To have a test coverage report, enter::

    py.test --cov=rstdoc --cov-report term-missing

Test Coverage
=============

The tests aim to produce 100% test coverage.


The current test coverage is this.

.. include:: _testcoverage.txt
    :literal:

Tests
=====

.. include:: _test_dcx_tests.rst

.. include:: _test_rst_table.rst


.. _`pytest`: https://docs.pytest.org/en/latest/
.. _`tox`: https://tox.readthedocs.io/en/latest/

.. include:: _links_sphinx.rst

