.. vi: syntax=rst

.. _`or1`:

======
rstdoc
======

Purpose
=======


.. include:: ../readme.rst


.. include:: _dcx.rst

.. include:: _dcx_api.rst



.. include:: _fromdocx.rst

.. include:: _fromdocx_api.rst



.. include:: _listtable.rst

.. include:: _listtable_api.rst


.. include:: _untable.rst

.. include:: _untable_api.rst


.. include:: _reflow.rst

.. include:: _reflow_api.rst


.. include:: _reimg.rst

.. include:: _reimg_api.rst


.. include:: _retable.rst

.. include:: _retable_api.rst



.. .. .. alternatively one could make a rstdoc.rest.stpl with
.. .. %import sys
.. .. %sys.path.append('..')
.. .. %from setup.py import read
.. .. 
.. .. {{read('readme.rst')}}
.. .. 
.. .. {{read('rstdoc/dcx.py')}}
.. .. 
.. .. {{read('rstdoc/fromdocx.py')}}
.. .. 
.. .. {{read('rstdoc/listtable.py')}}
.. .. 
.. .. {{read('rstdoc/untable.py')}}
.. .. 
.. .. {{read('rstdoc/reflow.py')}}
.. .. 
.. .. {{read('rstdoc/reimg.py')}}
.. .. 
.. .. {{read('rstdoc/retable.py')}}



.. .. repeat links here because pandoc does not see those in included file

.. _`substitutions`: http://docutils.sourceforge.net/docs/ref/rst/directives.html#replacement-text
.. _`vim-rst-tables-py3`: https://github.com/ossobv/vim-rst-tables-py3
.. _`vim_py3_rst`: https://github.com/rpuntaie/vim_py3_rst
.. _`editors`: http://build-me-the-docs-please.readthedocs.io/en/latest/Using_Sphinx/ToolsForReStructuredText.html
.. _`Emacs`: http://docutils.sourceforge.net/docs/user/emacs.html
.. _`ctags`: http://ctags.sourceforge.net/FORMAT
.. _`Sphinx`: http://www.sphinx-doc.org/en/stable/
.. _`Docutils`: http://docutils.sourceforge.net/
.. _`Pandoc`: https://pandoc.org/
.. _`RST`: http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html
.. _`DOCX`: http://www.ecma-international.org/publications/standards/Ecma-376.htm
.. _`SimpleTemplate`: https://bottlepy.org/docs/dev/stpl.html#simpletemplate-syntax
.. _`waf`: https://github.com/waf-project/waf

.. include:: _links_sphinx.rst


